### ISSUE TITLE
Signing with production - just an FYI

### ISSUE THREAD

**Issue by Covkie** [cawilliamson/rooted-graphene#1]
On the XDA forum:
> GOOGLE UPDATED DROIDGUARD, IF YOU ARE USING CUSTOM ROM, IT MUST BE SIGNED WITH PRODUCTION KEYS AND NOT WITH TEST KEYS. ASK YOUR ROM MAINTAINER IF YOUR ROM IS SIGNED

Seems any custom builds of GOS just got a little more annoying :p Implementing prod key signing to allow device integrity to pass is a must now.

**Comment by cawilliamson** [comment]
I don't *think* this will affect GOS in particular because it never passed device integrity did it? I didn't think you could pass device integrity on Graphene anyway due to the sandboxed gapps limitations? Am I missing something? :)
